# DevHive Configuration for Katorin2
# Sprint: i18n翻訳
version: "1"
project: Katorin2

defaults:
  base_branch: main
  auto_prompt: true
  auto_complete: true
  direnv_allow: true
  tool_args:
    claude: "--dangerously-skip-permissions --model sonnet"

workers:
  # 大会ページの翻訳
  tournament-i18n:
    branch: feat/tournament-i18n
    role: .devhive/roles/i18n-translator.md
    task: .devhive/tasks/tournament-i18n.md
    tool: claude

  # シリーズページの翻訳
  series-i18n:
    branch: feat/series-i18n
    role: .devhive/roles/i18n-translator.md
    task: .devhive/tasks/series-i18n.md
    tool: claude

  # 認証ページの翻訳
  auth-i18n:
    branch: feat/auth-i18n
    role: .devhive/roles/i18n-translator.md
    task: .devhive/tasks/auth-i18n.md
    tool: claude

  # マイページの翻訳
  mypage-i18n:
    branch: feat/mypage-i18n
    role: .devhive/roles/i18n-translator.md
    task: .devhive/tasks/mypage-i18n.md
    tool: claude

  # チームページの翻訳
  team-i18n:
    branch: feat/team-i18n
    role: .devhive/roles/i18n-translator.md
    task: .devhive/tasks/team-i18n.md
    tool: claude

  # レビュー担当（Opusを使用）
  reviewer:
    branch: review/i18n
    role: .devhive/roles/reviewer.md
    task: .devhive/tasks/i18n-reviewer.md
    tool: claude
    tool_args: "--dangerously-skip-permissions --model opus"
    no_worktree: true
