require "test_helper"

class SessionsFlowTest < ActionDispatch::IntegrationTest
  setup do
    @password = "password"
    @organizer_account = OrganizerAccount.create!(
      display_name: "Session Flow Organizer",
      login_id: "session-flow-admin",
      email: "session-flow-admin@example.com",
      password: @password
    )
    @organizer_account.organizer_members.create!(
      display_name: "Owner User",
      role: "owner",
      active: true,
      admin_password: "1234"
    )
  end

  test "login form generated by form_with url uses unscoped field names" do
    get new_session_path(locale: :ja)

    assert_response :success
    assert_select "form.login-form[action='#{session_path(locale: :ja)}']" do
      assert_select "input[name='login_id'][id='login_id']", 1
      assert_select "input[name='password'][id='password']", 1
      assert_select "input[name='session[login_id]']", 0
      assert_select "input[name='session[password]']", 0
    end
  end

  test "login succeeds with direct params from form_with url" do
    post session_path(locale: :ja), params: {
      login_id: @organizer_account.login_id,
      password: @password
    }

    assert_redirected_to new_member_selection_path(locale: :ja)
  end

  test "login succeeds with scoped session params" do
    post session_path(locale: :ja), params: {
      session: {
        login_id: @organizer_account.login_id,
        password: @password
      }
    }

    assert_redirected_to new_member_selection_path(locale: :ja)
  end
end
