steps:
  - name: gcr.io/cloud-builders/docker
    dir: apps/ledger
    args:
      - build
      - -f
      - Dockerfile.cloudrun
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
