RAILS_ENV: production
RAILS_LOG_LEVEL: info
APP_HOST: katorin2.codenica.dev
ACTIVE_JOB_ADAPTER: async
ACTIVE_STORAGE_SERVICE: local
RAILS_MASTER_KEY: REPLACE_ME
SECRET_KEY_BASE: REPLACE_ME
LEDGER_DATABASE_NAME: katorin2
LEDGER_DATABASE_USERNAME: app-user
LEDGER_DATABASE_PASSWORD: REPLACE_ME
LEDGER_DATABASE_HOST: /cloudsql/PROJECT:REGION:INSTANCE
